### ISSUE TITLE
Install fails on hass.io 0.115.6

### ISSUE THREAD

**Issue by rioloo** [matejdro/login_control#2]
When configuring token_control: in configuration.yaml i obatin this error:

`WARNING (MainThread) [homeassistant.loader] You are using a custom integration for token_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing token_control/media_source.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 401, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.login_control.media_source'
ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing token_control/logbook.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 401, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.login_control.logbook'
`

**Comment by matejdro** [comment]
Huh, I just updated to `0.116.1` and it seems to work fine. Have you modified the files in any way? How did you install it?

**Comment by rioloo** [comment]
I'm sorry, it fails on 0.116.1 and 0.116.2 too.
I obtain this:
<pre>
2020-10-11 23:53:38 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for token_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-11 23:53:41 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing token_control/group.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 401, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.login_control.group'
2020-10-11 23:53:41 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing token_control/logbook.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 401, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.login_control.logbook'
2020-10-11 23:53:41 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing token_control/media_source.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 401, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.login_control.media_source'
<pre>

**Comment by matejdro** [comment]
How did you install it?

**Comment by rioloo** [comment]
hass.io is running in docker container on a synology nas, here's my conf
<pre>
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /ssl/star.crt
  ssl_key: /ssl/star.key
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

# API
api:

# Ada
#stt: cloud
#tts: cloud
# Text-to-speech
tts:
  - platform: google_translate

# MariaDB database
recorder:
  db_url: mysql://user:password@dbhost/homeassistant?charset=utf8

# Logging
logger:
  default: error
  #default: warn
  #default: info
  #default: debug

system_log:
  max_entries: 100
    
# Frontend
frontend:
  #javascript_version: latest
  themes: !include_dir_merge_named themes

# Modules
ffmpeg:
stream:
wake_on_lan:

# Customs entities
camera: !include entities_camera.yaml
sensor: !include entities_sensor.yaml
switch: !include entities_switch.yaml
webostv: !include entities_webostv.yaml
media_player: !include entities_mplayer.yaml
synology_dsm: !include entities_nas.yaml
alarm_control_panel: !include alarms.yaml

# Group, automations, script, scense
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

token_control:

# Auth
homeassistant:
  customize: !include customize.yaml
  auth_providers:
    - type: command_line
      command: /share/ldap/ldap-auth.sh
      meta: true
    - type: trusted_networks
      allow_bypass_login: true
      trusted_networks:
        [...]
      trusted_users:
        [...]
</pre>

here's login_control
<pre>
# ls -l custom_components/login_control/
total 12
-rw-r--r--  1 root root 551 Oct  7 23:59 __init__.py
-rw-r--r--  1 root root 224 Oct  7 23:32 manifest.json
d---------+ 1 root root  46 Oct  8 00:07 __pycache__
-rw-r--r--  1 root root 132 Oct  7 23:33 services.yaml
</pre>

edit: tried with 0.116.4, no luck

**Comment by matejdro** [comment]
It looks like you have `token_control:` in the config, while it should be `login_control:`

**Comment by rioloo** [comment]
It works, thanks.
