### ISSUE TITLE
TypeError: object NoneType can't be used in 'await' expression`

### ISSUE THREAD

**Issue by qntris** [matejdro/login_control#4]
I am calling your script using the Dev Tools in Home Assistant, passing a valid  user_id. The tokens are indeed cleared, but this message appears in the logs:

`Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:525
First occurred: 16:20:50 (1 occurrences)
Last logged: 16:20:50

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/login_control/__init__.py", line 14, in handle_refresh_token_clear
    await hass.auth.async_remove_refresh_token(token)
TypeError: object NoneType can't be used in 'await' expression`

**Comment by matejdro** [comment]
Thanks for the report. Fixed with https://github.com/matejdro/login_control/commit/b15f725e126a5fce806e70a4721a9d2fa2069557
